[config]
layout = "Night"
selection = { "All" = [] }
game = ["Intro"]
modify = { give = -1, next = { stage = 1, level = 1 } }
sun = 0
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[4, 5], [1, 1], [2, 1], [3, 1], [5, 5], [6, 5]]
avail = []
