[config]
selection = "Any"
layout = "Roof"
modify = { give = -35, next = [5, 3] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2]]
avail = []
[[waves]]
points = 150
wait = 50.0
big = false
fixed = []
avail = [1, 2, 3, 7]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 1], [2, 1], [15, 1]]
avail = []
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[7, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 60.0
big = true
fixed = [[4, 1], [12, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[13, 1]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[1, 2]]
avail = [3, 7]
[[waves]]
points = 275
wait = 40.0
big = false
fixed = [[2, 1], [12, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 1], [13, 1], [15, 1]]
avail = [1, 2, 3, 7]
