[config]
selection = "Any"
layout = "Roof"
modify = { give = 0, next = { stage = 5, level = 5 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[11, 1]]
avail = [1]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[2, 1]]
avail = [1, 2, 3]
[[waves]]
points = 150
wait = 50.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 60.0
big = true
fixed = [[4, 1], [13, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[2, 1], [7, 1]]
avail = [1, 3]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[11, 1]]
avail = [1, 2, 13]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[13, 1], [15, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[1, 2]]
avail = [2, 3, 7, 13]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 2], [5, 1], [15, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[1, 3], [13, 3]]
avail = [3, 7, 13, 15]
[[waves]]
points = 350
wait = 40.0
big = false
fixed = [[11, 2]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 50.0
big = false
fixed = [[5, 1], [15, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[3, 2], [15, 1]]
avail = [1, 2, 7, 13]
[[waves]]
points = 700
wait = 60.0
big = true
fixed = [[4, 3], [5, 2], [11, 1], [15, 2]]
avail = [1, 2, 3, 5, 7, 13, 15]
