[config]
selection = "Any"
layout = "Roof"
game = ["Columns"]
modify = { give = -37, next = [5, 6] }
sun = 150
bgm = "Ub"
publish = { name = "Columns Like You See 'Em" }
[[waves]]
points = 0
wait = 10.0
big = false
fixed = [[2, 5], [1, 5]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[3, 5], [1, 5]]
avail = []
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 5], [6, 5], [5, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[6, 5], [11, 4]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 5], [6, 5], [5, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[4, 1], [1, 5], [3, 5], [5, 3], [12, 5]]
avail = [1, 2, 3, 6, 7, 13]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[2, 10], [3, 5], [13, 5]]
avail = [1, 2, 3, 7, 13]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[5, 3], [13, 4], [15, 2], [5, 2]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[11, 5], [6, 5], [3, 5]]
avail = [1, 2, 3, 7, 13, 15]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[15, 3], [6, 3], [7, 3], [5, 2]]
avail = [1, 2, 3, 7, 13, 15]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[15, 5], [10, 3], [6, 3]]
avail = [1, 2, 3, 7, 13, 15]
[[waves]]
points = 600
wait = 40.0
big = false
fixed = [[7, 5], [8, 5], [13, 10]]
avail = [1, 2, 3, 6, 7, 13, 15]
[[waves]]
points = 600
wait = 30.0
big = false
fixed = [[11, 3], [5, 2], [8, 2]]
avail = [1, 2, 3, 7, 13, 15]
[[waves]]
points = 700
wait = 40.0
big = false
fixed = [[3, 10], [2, 10]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 700
wait = 40.0
big = false
fixed = [[13, 5], [15, 5]]
avail = [1, 2, 3, 7, 13, 15]
[[waves]]
points = 1000
wait = 50.0
big = true
fixed = [[11, 5], [5, 5], [15, 5], [13, 5]]
avail = [1, 2, 3, 6, 7, 13, 15]
