[config]
selection = "Any"
layout = "Roof"
modify = { give = 0, next = { stage = 5, level = 5 } }
sun = 9990
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[5, 1], [1, 1], [13, 2], [15, 1]]
avail = []
