[config]
selection = "Any"
layout = "Roof"
modify = { give = -39, next = [5, 8] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2], [6, 1]]
avail = []
[[waves]]
points = 175
wait = 30.0
big = false
fixed = [[15, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 250
wait = 60.0
big = true
fixed = [[4, 1], [15, 1], [11, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 250
wait = 40.0
big = false
fixed = [[1, 1], [6, 2]]
avail = [2, 3, 7]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[13, 1], [7, 1]]
avail = [1, 2, 3, 6, 7, 13]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 1], [6, 1], [16, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 2], [1, 3], [11, 1], [13, 1], [15, 2]]
avail = [1, 2, 3, 6, 7, 13]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[1, 1], [16, 1]]
avail = [2, 3]
[[waves]]
points = 400
wait = 50.0
big = false
fixed = [[1, 2], [11, 2], [15, 1]]
avail = [2, 3, 6, 7]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[13, 3], [15, 2]]
avail = [1, 2, 3, 7, 13, 15]
[[waves]]
points = 650
wait = 60.0
big = true
fixed = [[4, 3], [11, 1], [16, 3]]
avail = [1, 2, 3, 6, 7, 13, 15]
