[config]
selection = "Any"
layout = "Roof"
modify = { give = -40, next = [5, 9] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [2, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[13, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [7, 1], [8, 1]]
avail = []
[[waves]]
points = 150
wait = 50.0
big = false
fixed = [[1, 1], [15, 1]]
avail = [1, 2]
[[waves]]
points = 200
wait = 60.0
big = true
fixed = [[4, 1], [16, 1]]
avail = [1, 2, 3, 13]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[8, 1], [17, 1]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[8, 1], [13, 1], [15, 2]]
avail = [2, 3]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[17, 1], [16, 1]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 30.0
big = false
fixed = [[1, 1], [2, 2], [3, 1], [7, 1]]
avail = [13, 15]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 2], [15, 1], [16, 1], [17, 1]]
avail = [1, 2, 3, 7, 13]
[[waves]]
points = 400
wait = 50.0
big = false
fixed = [[3, 1], [17, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 450
wait = 40.0
big = false
fixed = [[1, 2], [7, 1], [8, 1], [16, 1]]
avail = [2, 3, 13]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[16, 1], [17, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[8, 2], [15, 2], [17, 1]]
avail = [1, 2, 3]
[[waves]]
points = 800
wait = 60.0
big = true
fixed = [[4, 3], [15, 2], [16, 2], [17, 3]]
avail = [1, 2, 3, 7, 13]
