[config]
selection = "Any"
layout = "Roof"
modify = { give = 0, next = [5, 10], unlock = [
    [1, 11],
] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 2]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[3, 1], [7, 1]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 2], [5, 1]]
avail = []
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[6, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 60.0
big = true
fixed = [[4, 1], [17, 1]]
avail = [1, 2, 13]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [3, 1], [6, 1], [16, 1]]
avail = []
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[1, 2], [5, 1], [6, 1]]
avail = [2, 3, 7]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[3, 1], [11, 1], [17, 1]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 2], [6, 2], [16, 2]]
avail = [1, 2, 3, 7, 13]
[[waves]]
points = 250
wait = 30.0
big = false
fixed = [[5, 1], [7, 1], [11, 1]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 50.0
big = false
fixed = [[10, 1], [17, 2]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[11, 1], [16, 1]]
avail = [2, 3, 6, 7, 13]
[[waves]]
points = 700
wait = 60.0
big = true
fixed = [[4, 3], [5, 1], [16, 2]]
avail = [1, 2, 3, 6, 7, 13]
[[waves]]
points = 550
wait = 50.0
big = false
fixed = [[6, 3], [11, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 550
wait = 40.0
big = false
fixed = [[1, 2], [10, 2], [17, 3]]
avail = [2, 3, 7]
[[waves]]
points = 650
wait = 40.0
big = false
fixed = [[3, 1], [16, 2], [17, 1]]
avail = [1, 3, 5, 7]
[[waves]]
points = 900
wait = 60.0
big = true
fixed = [[4, 4], [1, 1], [11, 1], [16, 3], [17, 3]]
avail = [2, 3, 5, 6, 7, 10, 11, 13]
