[config]
selection = "Any"
layout = "Fog"
modify = { give = -27, next = [4, 3] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[2, 1]]
avail = []
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[1, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[12, 1]]
avail = [1, 2]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[9, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 60.0
big = true
fixed = [[4, 1], [11, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 175
wait = 40.0
big = false
fixed = [[1, 1], [12, 1]]
avail = [2, 3, 7]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [3, 1], [7, 1], [9, 1]]
avail = []
[[waves]]
points = 250
wait = 40.0
big = false
fixed = [[1, 1], [7, 1]]
avail = [2, 3, 9]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[1, 2], [2, 1], [12, 1]]
avail = [3, 7]
[[waves]]
points = 400
wait = 60.0
big = false
fixed = [[1, 1], [11, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 2], [9, 1], [11, 1], [12, 1]]
avail = [1, 2, 3, 7]
