[config]
selection = "Any"
layout = "Fog"
modify = { give = 0, next = { stage = 4, level = 5 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[2, 1], [3, 1]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = []
avail = [1, 2]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[6, 1]]
avail = [1, 2, 7]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[1, 1], [9, 1]]
avail = [1, 2, 7]
[[waves]]
points = 250
wait = 60.0
big = true
fixed = [[4, 1], [1, 1], [13, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[7, 1], [12, 1]]
avail = [2, 3, 9]
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[11, 1], [13, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = []
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[6, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[12, 2]]
avail = [1, 2, 3, 6, 9]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 2], [3, 1], [11, 2], [13, 1]]
avail = []
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 2], [5, 1], [6, 1]]
avail = [1, 2, 3, 7, 9, 13]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[1, 1], [6, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[2, 1], [12, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 350
wait = 40.0
big = false
fixed = [[1, 1], [11, 2], [13, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[1, 1], [6, 2], [9, 2]]
avail = [1, 2, 3, 6, 7, 13]
[[waves]]
points = 600
wait = 60.0
big = false
fixed = [[4, 3], [5, 1], [11, 1], [12, 2], [13, 2]]
avail = [1, 2, 3, 7, 13]
