[config]
selection = { "All" = [-17, -25, -10, -10, -10, -10, -10, -10] }
layout = "Fog"
game = ["Random"]
modify = { give = -29, next = [4, 6] }
sun = 200
bgm = "Lb"
publish = { name = "Randomness" }
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 1], [2, 1]]
avail = []
[[waves]]
points = 150
wait = 50.0
big = false
fixed = [[9, 1]]
avail = [1, 2]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[2, 1]]
avail = [1, 2, 3]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[6, 1]]
avail = [1, 2]
[[waves]]
points = 200
wait = 60.0
big = true
fixed = [[4, 1], [3, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[7, 1], [12, 1]]
avail = [1, 2, 3]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[1, 1], [10, 1]]
avail = [2, 3, 6, 9]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 1], [5, 1], [6, 1]]
avail = []
[[waves]]
points = 250
wait = 40.0
big = false
fixed = [[1, 2], [9, 1]]
avail = [3, 6, 7]
[[waves]]
points = 300
wait = 60.0
big = true
fixed = [[4, 2], [10, 1], [12, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[6, 1], [11, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 1], [12, 1]]
avail = [2, 3, 7, 9]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[3, 1], [5, 1], [9, 1]]
avail = [1, 2, 3]
[[waves]]
points = 350
wait = 60.0
big = true
fixed = [[4, 3], [10, 1], [12, 1]]
avail = [1, 2, 3, 6, 7, 9]
