[config]
selection = "Any"
layout = "Fog"
game = "Adventure"
modify = { give = -31, next = { stage = 4, level = 8 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 2], [2, 1]]
avail = []
[[waves]]
points = 100
wait = 50.0
big = false
fixed = [[14, 1]]
avail = [1, 2]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [7, 1], [9, 1]]
avail = []
[[waves]]
points = 100
wait = 50.0
big = false
fixed = [[1, 1], [3, 1]]
avail = [1, 2]
[[waves]]
points = 200
wait = 60.0
big = true
fixed = [[4, 1], [13, 1]]
avail = [1, 3, 7]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[12, 1]]
avail = [1, 3, 7]
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[14, 1]]
avail = [1, 2, 9]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[3, 2], [7, 2]]
avail = [1]
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[13, 2]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 60.0
big = true
fixed = [[4, 2], [12, 1], [9, 2]]
avail = [2, 3, 7]
[[waves]]
points = 150
wait = 30.0
big = false
fixed = [[3, 2], [9, 1]]
avail = [1, 2]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[2, 1], [13, 1]]
avail = [1, 3, 7]
[[waves]]
points = 350
wait = 50.0
big = false
fixed = [[12, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 3], [14, 2]]
avail = [1, 2, 3, 7, 12, 13]
