[config]
selection = { "All" = [-2, -17, -18, -19, -20, -21, -22, -23, -24] }
layout = "Pool"
modify = { give = -25, next = { stage = 4, level = 1 }, slots = 9 }
sun = 1500
bgm = "Ub"
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[1, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = true
fixed = [
    [
        4,
        1,
    ],
    [
        1,
        1,
    ],
    [
        2,
        1,
    ],
    [
        3,
        1,
    ],
    [
        5,
        1,
    ],
    [
        6,
        1,
    ],
    [
        7,
        1,
    ],
    [
        8,
        1,
    ],
    [
        9,
        1,
    ],
    [
        10,
        1,
    ],
    [
        11,
        1,
    ],
]
avail = []
[[waves]]
points = 300
wait = 80.0
big = true
fixed = [[4, 2], [10, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 3], [5, 1]]
avail = [1, 2, 3, 6, 7, 8, 9]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 4], [11, 2]]
avail = [1, 2, 3, 6, 7, 9]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 5], [3, 1], [7, 1], [8, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[4, 6], [5, 1], [10, 2]]
avail = [1, 2, 3, 7, 8, 9]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 7], [6, 3], [8, 2], [10, 1], [11, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 8], [9, 2], [11, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 600
wait = 60.0
big = true
fixed = [[4, 9], [5, 2], [6, 2]]
avail = [1, 2, 3, 7, 8]
[[waves]]
points = 600
wait = 60.0
big = true
fixed = [[4, 10], [5, 1], [10, 1], [11, 2]]
avail = [1, 2, 3, 7, 8, 9]
[[waves]]
points = 700
wait = 60.0
big = true
fixed = [[4, 11], [5, 1], [11, 3]]
avail = [1, 2, 3, 6, 7, 9]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[4, 12], [6, 4]]
avail = [1, 2, 3, 7]
[[waves]]
points = 800
wait = 60.0
big = true
fixed = [[4, 13], [6, 2], [8, 2], [10, 2], [11, 2]]
avail = [1, 2, 3, 6, 7, 8, 9]
[[waves]]
points = 1300
wait = 80.0
big = true
fixed = [[4, 14], [5, 1], [10, 1], [11, 1]]
avail = [1, 2, 3, 5, 6, 7, 8, 9, 10, 11]
