[config]
selection = "Any"
layout = "Pool"
modify = { give = 0, next = [3, 12] }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [3, 1]]
avail = []
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[302, 1]]
avail = [2, 3, 7]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 3], [3, 2], [5, 1], [6, 1]]
avail = []
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[1, 1], [10, 1]]
avail = [2, 3, 302]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[5, 1], [302, 2]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[301, 1], [5, 1], [10, 1]]
avail = [2, 3, 6]
[[waves]]
points = 600
wait = 30.0
big = false
fixed = [[7, 1], [304, 1]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[1, 3], [10, 2]]
avail = [2, 3, 6, 7, 302]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[6, 2], [304, 2]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[1, 3], [302, 1], [5, 2]]
avail = [2, 3, 6, 302, 304]
[[waves]]
points = 700
wait = 50.0
big = true
fixed = [[301, 2], [1, 5], [10, 2], [5, 2]]
avail = [1, 2, 3, 6, 7, 302]
