[config]
selection = "Any"
layout = "Pool"
game = "Adventure"
modify = { give = -20, next = { stage = 3, level = 4 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 1], [9, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [3, 1], [9, 1]]
avail = []
[[waves]]
points = 300
wait = 50.0
big = false
fixed = []
avail = [1, 2, 3, 7, 8, 9]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 1], [5, 1], [9, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[1, 2], [6, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [3, 1], [5, 1], [6, 1]]
avail = []
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[7, 1], [6, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 2], [8, 3]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 600
wait = 60.0
big = true
fixed = [[4, 2], [5, 2]]
avail = [1, 2, 3, 6, 7, 8, 9]
[[waves]]
points = 250
wait = 40.0
big = false
fixed = [[1, 2], [6, 2], [9, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 350
wait = 50.0
big = false
fixed = [[1, 1], [5, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[3, 1], [6, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[2, 1], [8, 1], [9, 1]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 800
wait = 60.0
big = true
fixed = [[4, 3], [1, 3], [5, 2], [6, 2]]
avail = [1, 2, 3, 5, 6, 7, 8, 9]
