[config]
selection = "Any"
layout = "Pool"
game = "Adventure"
modify = { give = -20, next = { stage = 3, level = 4 } }
sun = 99999
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[9, 1], [8, 1], [6, 1], [3, 1], [7, 1]]
avail = []
