[config]
selection = "Any"
layout = "Pool"
modify = { give = 0, next = [3, 10] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [2, 1]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 1], [2, 1]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[11, 1]]
avail = []
[[waves]]
points = 125
wait = 50.0
big = false
fixed = [[1, 1]]
avail = [1, 2, 3, 9]
[[waves]]
points = 125
wait = 40.0
big = false
fixed = [[9, 1]]
avail = [1, 2, 3]
[[waves]]
points = 100
wait = 40.0
big = false
fixed = [[5, 1], [6, 1]]
avail = [1, 2]
[[waves]]
points = 225
wait = 60.0
big = true
fixed = [[4, 1], [10, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[3, 1], [6, 1]]
avail = [1, 2, 9]
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[6, 3]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 30.0
big = false
fixed = [[11, 2]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[9, 2], [10, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 2], [2, 1], [5, 2]]
avail = [1, 2, 3, 7, 9]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 2], [7, 1], [6, 1], [10, 2]]
avail = []
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[5, 1], [10, 1], [11, 1]]
avail = [1, 2, 9]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[6, 3], [11, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 500
wait = 50.0
big = false
fixed = [[1, 1], [5, 1], [10, 1]]
avail = [1, 2, 3, 6, 7, 9]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 3], [5, 2], [10, 3], [11, 3]]
avail = [1, 2, 3, 6, 7, 9]
