[config]
selection = { "All" = [-9, -10, -11, -12, -13, -14, -15, -16] }
layout = "Night"
modify = { give = -17, next = { stage = 3, level = 1 }, slots = 8 }
sun = 1000
bgm = "Ub"
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[1, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = true
fixed = [[4, 1], [1, 1], [2, 1], [3, 1], [5, 1], [6, 1], [7, 1], [8, 1]]
avail = []
[[waves]]
points = 400
wait = 40.0
big = true
fixed = [[4, 2], [1, 1], [2, 1], [3, 1]]
avail = [1, 2, 3, 5, 6, 7, 8]
[[waves]]
points = 500
wait = 60.0
big = true
fixed = [[4, 3], [1, 1], [2, 1], [3, 1], [5, 1]]
avail = [1, 2, 3, 6, 7, 8]
[[waves]]
points = 600
wait = 60.0
big = true
fixed = [[4, 3], [1, 3], [3, 1], [5, 1]]
avail = [2, 3, 5, 6, 7, 8]
[[waves]]
points = 600
wait = 80.0
big = true
fixed = [[4, 4], [2, 2], [3, 1], [6, 3]]
avail = [1, 2, 3, 7, 8]
[[waves]]
points = 700
wait = 60.0
big = true
fixed = [[4, 5], [1, 4], [8, 5]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 700
wait = 50.0
big = true
fixed = [[4, 6], [3, 2], [6, 2], [7, 2]]
avail = [1, 2, 3, 5, 6, 7, 8]
[[waves]]
points = 800
wait = 60.0
big = true
fixed = [[4, 7], [3, 1], [5, 1]]
avail = [1, 2, 3, 5, 6, 7, 8]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[4, 8], [5, 1]]
avail = [1, 2, 3, 5, 6, 7, 8]
[[waves]]
points = 800
wait = 60.0
big = true
fixed = [[4, 9], [5, 1], [6, 2]]
avail = [1, 2, 3, 5, 6, 7, 8]
[[waves]]
points = 800
wait = 80.0
big = true
fixed = [[4, 10], [1, 5], [5, 3], [6, 3]]
avail = [2, 3, 5, 6, 7, 8, 101]
