[config]
selection = "Any"
layout = "Night"
modify = { give = 0, next = [2, 12] }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1], [3, 1]]
avail = []
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[1, 1], [8, 1]]
avail = [3, 7]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[302, 1]]
avail = [1, 2, 7]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[3, 2], [2, 2]]
avail = [1, 2, 3, 7, 8]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[8, 2], [7, 1], [2, 2], [1, 3]]
avail = [2, 3, 7, 302]
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[301, 1], [302, 2], [1, 3]]
avail = [2, 3, 7]
