[config]
selection = "Any"
layout = "Night"
modify = { give = 0, next = [2, 14] }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 2], [6, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3], [3, 1], [304, 1]]
avail = []
[[waves]]
points = 250
wait = 40.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 50.0
big = true
fixed = [[301, 1], [8, 1], [302, 2]]
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[1, 3], [6, 1], [304, 1]]
avail = [2, 3, 7]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[2, 2], [302, 2], [6, 2]]
avail = [1, 3, 5, 8]
[[waves]]
points = 350
wait = 30.0
big = false
fixed = [[1, 3], [5, 1], [304, 1]]
avail = [3, 6, 7, 8]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[2, 2], [5, 1], [6, 1], [302, 2]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[301, 1], [5, 1], [302, 2], [304, 3]]
avail = [1, 2, 3, 7, 8]
