[config]
selection = "Any"
layout = "Night"
modify = { give = 0, next = { stage = 2, level = 13 } }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1], [11, 1]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[3, 1], [302, 1]]
avail = [1, 2, 7]
[[waves]]
points = 350
wait = 50.0
big = true
fixed = [[301, 1], [7, 1], [304, 1]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[1, 3]]
avail = [2, 3, 7]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[302, 2], [11, 1]]
avail = [1, 2, 3, 304]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[10, 1], [3, 2], [2, 2]]
avail = [1, 304, 7]
[[waves]]
points = 600
wait = 50.0
big = true
fixed = [[301, 2], [1, 1], [11, 2], [10, 1], [304, 1]]
avail = [2, 3, 7, 302]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 5], [2, 5], [3, 3], [302, 3]]
avail = []
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[11, 3]]
avail = [1, 2, 3, 7]
[[waves]]
points = 600
wait = 40.0
big = false
fixed = [[10, 1], [304, 1]]
avail = [2, 3, 7]
[[waves]]
points = 700
wait = 50.0
big = true
fixed = [[301, 3], [1, 3], [10, 2]]
avail = [2, 3, 7, 11, 302, 304]
