[config]
selection = "Any"
layout = "Night"
game = ["WhackAZombie"]
modify = { give = 0, next = { stage = 2, level = 13 } }
sun = 0xbadeffec
bgm = "Lb"
publish = { name = "Whack a Zombie (Ex)" }
[conveyor]
items = [
    [
        -11,
        { max = 5, weight = 2.0 },
    ],
    [
        -10,
        { max = 5, weight = 5.0 },
    ],
    [
        -8,
        { max = 10, weight = 5.0 },
    ],
    [
        -3,
        { max = 3, weight = 1.0 },
    ],
]
interval = 5.0
speed = 0.3
[[waves]]
points = 0
wait = 10.0
big = false
fixed = [[1, 5], [2, 1]]
avail = []
[[waves]]
points = 0
wait = 10.0
big = false
fixed = [[1, 5], [2, 1], [3, 1], [5, 1]]
avail = []
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[11, 1], [6, 1], [302, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[10, 1], [5, 1], [7, 1], [8, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 400
wait = 10.0
big = false
fixed = [[12, 2], [11, 1], [6, 3]]
avail = [1, 2, 3, 8]
[[waves]]
points = 300
wait = 30.0
big = true
fixed = [[301, 1], [11, 2], [13, 1], [14, 2]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[10, 1], [11, 1], [6, 1], [302, 1], [304, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[304, 1], [15, 1], [16, 1], [17, 1]]
avail = [1, 2, 3, 7, 8]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[10, 2], [11, 2], [8, 2]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[5, 1], [3, 1], [6, 1], [304, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[5, 2], [15, 2], [16, 1]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 30.0
big = true
fixed = [[302, 1], [5, 1], [304, 1], [12, 1], [13, 1], [14, 2], [16, 2]]
avail = [1, 2, 3, 6, 7]
