[config]
selection = "Any"
layout = "Night"
modify = { give = 0, next = [2, 17] }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 2]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1], [6, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [305, 1]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[1, 1], [11, 1], [302, 1]]
avail = [2, 3]
[[waves]]
points = 400
wait = 50.0
big = true
fixed = [[301, 1], [1, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3], [2, 2], [3, 2], [6, 1], [302, 1]]
avail = []
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[302, 1], [305, 1], [3, 1]]
avail = [1, 2, 7, 11]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[1, 2], [302, 2], [11, 1]]
avail = [2, 3, 6]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[305, 2], [6, 2]]
avail = [1, 2, 3]
[[waves]]
points = 600
wait = 50.0
big = true
fixed = [[301, 2], [1, 3], [11, 1], [305, 2]]
avail = [2, 3, 6]
