[config]
selection = "Any"
layout = "Night"
modify = { give = 0, next = { stage = 2, level = 18 } }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [3, 2]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [304, 1]]
avail = []
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[1, 1], [305, 1]]
avail = [1, 2]
[[waves]]
points = 400
wait = 50.0
big = true
fixed = [[301, 1], [303, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[3, 2], [7, 1], [304, 1]]
avail = [1, 2]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[303, 1], [305, 2]]
avail = [1, 3, 7]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[7, 1], [304, 2]]
avail = [1, 2, 3]
[[waves]]
points = 600
wait = 50.0
big = true
fixed = [[301, 2], [1, 2], [303, 1], [305, 1]]
avail = [2, 3, 7]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[1, 3], [304, 1]]
avail = [2, 3, 7, 305]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[303, 1], [304, 2], [305, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 600
wait = 30.0
big = false
fixed = [[3, 2], [305, 2], [5, 1]]
avail = [1, 2, 7, 303]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[301, 3], [1, 2], [304, 2], [303, 2]]
avail = [1, 2, 7, 304, 305]
