[config]
selection = "Any"
layout = "Night"
modify = { give = 0, next = { stage = 2, level = 18 } }
sun = 9950
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [306, 1]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[11, 1], [302, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[1, 2], [305, 1]]
avail = [2, 3, 11]
[[waves]]
points = 400
wait = 50.0
big = true
fixed = [[301, 1], [302, 2]]
avail = [1, 2, 3, 11]
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[8, 1], [306, 1]]
avail = [1, 2]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[302, 1], [3, 2]]
avail = [1, 2]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[305, 1], [306, 1]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[11, 2], [302, 1]]
avail = [1, 2, 3]
[[waves]]
points = 600
wait = 50.0
big = true
fixed = [[301, 2], [302, 1], [306, 2]]
avail = [2, 3, 11, 302]
