[config]
selection = "Any"
layout = "Night"
modify = { give = -11, next = { stage = 2, level = 3 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2], [3, 1]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[6, 1]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 60.0
big = false
fixed = [[1, 2], [3, 1]]
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 80.0
big = true
fixed = [[4, 1], [1, 2], [5, 1], [6, 1]]
avail = [1, 2, 3]
[[waves]]
points = 350
wait = 50.0
big = false
fixed = []
avail = [1, 2, 3, 6]
[[waves]]
points = 350
wait = 60.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3, 6]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 3], [2, 3]]
avail = [1, 2, 3]
[[waves]]
points = 600
wait = 70.0
big = true
fixed = [[4, 2], [1, 5], [5, 1], [6, 1]]
avail = [1, 2, 3, 5, 6]
