[config]
selection = "Any"
layout = "Night"
game = "Adventure"
modify = { give = -12, next = { stage = 2, level = 4 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = []
avail = [1, 2, 3]
[[waves]]
points = 125
wait = 60.0
big = false
fixed = [[1, 1], [2, 1], [6, 1]]
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 80.0
big = true
fixed = [[1, 3], [5, 1]]
avail = [1, 2, 3, 6]
[[waves]]
points = 150
wait = 50.0
big = false
fixed = [[1, 2], [2, 2]]
avail = [1, 2, 3]
[[waves]]
points = 150
wait = 60.0
big = false
fixed = [[1, 2], [3, 1]]
avail = [1, 2, 3]
[[waves]]
points = 150
wait = 60.0
big = false
fixed = [[2, 1], [5, 1], [6, 1]]
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[1, 2], [6, 1]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 80.0
big = true
fixed = [[6, 1]]
avail = [1, 2, 3, 5, 6]
