[config]
selection = { "All" = [-3, -11] }
layout = "Night"
game = ["WhackAZombie"]
modify = { give = -13, next = [2, 6] }
sun = 0
bgm = "Lb"
publish = { name = "Whack a Zombie" }
[[waves]]
points = 300
wait = 20.0
big = false
fixed = []
avail = [1, 2]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[1, 5]]
avail = [2, 3]
[[waves]]
points = 400
wait = 10.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[3, 1], [6, 2]]
avail = [1, 2, 3, 7]
[[waves]]
points = 300
wait = 10.0
big = false
fixed = [[7, 3]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 500
wait = 10.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 1000
wait = 20.0
big = true
fixed = [[4, 1], [5, 1]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 100
wait = 10.0
big = false
fixed = [[3, 2], [7, 5]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 500
wait = 10.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 500
wait = 10.0
big = false
fixed = [[6, 3]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 600
wait = 10.0
big = false
fixed = [[5, 1], [6, 1], [7, 1]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 800
wait = 10.0
big = false
fixed = []
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 1200
wait = 20.0
big = true
fixed = [[4, 2], [3, 3]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 400
wait = 15.0
big = false
fixed = [[5, 3]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 500
wait = 10.0
big = false
fixed = [[6, 5]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 600
wait = 10.0
big = false
fixed = [[5, 1], [7, 1]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 700
wait = 10.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 2000
wait = 30.0
big = true
fixed = [[4, 3], [6, 1]]
avail = [1, 2, 3, 5, 6, 7]
