[config]
selection = "Any"
layout = "Night"
modify = { give = -14, next = [2, 7] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 2]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 3], [6, 1]]
avail = []
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[1, 2], [7, 1]]
avail = [1, 2, 3, 6]
[[waves]]
points = 400
wait = 80.0
big = true
fixed = [[4, 1], [2, 1], [3, 1], [5, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 0
wait = 60.0
big = false
fixed = [[2, 1], [6, 3]]
avail = []
[[waves]]
points = 275
wait = 50.0
big = false
fixed = [[3, 1], [7, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[6, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 500
wait = 50.0
big = false
fixed = [[5, 1], [6, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 1000
wait = 70.0
big = true
fixed = [[4, 2], [1, 2], [2, 2], [3, 1], [6, 1]]
avail = [1, 2, 3, 5, 6, 7]
