[config]
selection = "Any"
layout = "Night"
game = "Adventure"
modify = { give = -15, next = { stage = 2, level = 8 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[6, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [3, 1]]
avail = []
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[1, 1], [5, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 250
wait = 60.0
big = false
fixed = [[6, 1], [7, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 500
wait = 80.0
big = true
fixed = [[4, 1], [1, 2], [7, 1]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 3], [2, 2], [6, 1]]
avail = []
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[3, 2]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 200
wait = 60.0
big = false
fixed = [[5, 1], [1, 5], [2, 3], [7, 1]]
avail = [1, 3, 7]
[[waves]]
points = 300
wait = 60.0
big = false
fixed = [[1, 2], [7, 2]]
avail = [2, 5, 6]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[5, 2], [6, 2]]
avail = [1, 2, 3]
[[waves]]
points = 800
wait = 70.0
big = true
fixed = [[4, 2], [5, 1], [6, 1], [7, 1]]
avail = [1, 2, 3, 5, 6, 7]
