[config]
selection = "Any"
layout = "Night"
modify = { give = -16, next = { stage = 2, level = 9 } }
sun = 50
[[waves]]
points = 100
wait = 30.0
big = false
fixed = [[3, 1]]
avail = [1, 2]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [8, 1]]
avail = []
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[1, 2], [7, 1]]
avail = [1, 2]
[[waves]]
points = 250
wait = 60.0
big = false
fixed = [[1, 2], [6, 1]]
avail = [2, 3, 7]
[[waves]]
points = 400
wait = 80.0
big = true
fixed = [[4, 1], [5, 1], [7, 1]]
avail = [1, 2, 3, 7]
[[waves]]
points = 200
wait = 60.0
big = false
fixed = [[2, 2], [3, 1]]
avail = [1, 2, 3, 6, 7, 8]
[[waves]]
points = 300
wait = 60.0
big = false
fixed = [[8, 2]]
avail = [1, 2]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[1, 1], [5, 2]]
avail = [1, 2, 3, 6, 7]
[[waves]]
points = 800
wait = 70.0
big = true
fixed = [[4, 2], [1, 3]]
avail = [2, 3, 6, 7, 8]
[[waves]]
points = 300
wait = 60.0
big = false
fixed = [[1, 1], [5, 1], [6, 1]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 50.0
big = false
fixed = [[1, 2], [5, 1], [8, 1]]
avail = [1, 2, 3, 6, 7, 8]
[[waves]]
points = 800
wait = 70.0
big = true
fixed = [[4, 3], [5, 2], [6, 1]]
avail = [1, 2, 3, 7, 8]
