[desc.peashooter]
name = "Pisum sativum var. chlorojaculum"
short = "You would not see this anyway"
desc = """Shoots peas at zombies
Damage: Regular"""
[desc.sunflower]
name = "Helianthus annuus"
short = "Gives you more sun"
desc = """Throws sun that you can pick up, or not, I don't care anyway
Damage: Why Ask"""
[desc.cherry_bomb]
name = "Prunus avium"
short = "Blows up zombies in an area"
desc = """Deals great damage to zombies in an area(smaller than 3x3)]
Damage: SUPER
Works when planted"""
[desc.wall_nut]
name = "Juglans regia"
short = "Blocks zombies with its high health"
desc = """Blocks zombies
Damage: Not Again
Health: High"""
[desc.potato_mine]
name = "Solanum tuberosum"
short = "Blows up a small area of zombies on touch, takes time to arm himself"
desc = """Blows up a small area of zombies on touch, takes time to arm himself
Damage: SUPER
Takes time to be usable"""
[desc.snow_pea]
name = "Pisum sativum var. macrocarpum"
short = "Shoots peas that slow down zombies"
desc = """Shoots snow peas that can slow down zombies while dealing damage
Damage: Regular
Slows down zombies"""
[desc.repeater]
name = "Pisum sativum var. dijaculum"
short = "Shoots two peas at a time"
desc = """Shoots two peas at a time, saving you some space
Damage: Double"""
[desc.iceberg_lettuce]
name = "Lactuca sativa var. capitata"
short = "Freezes the first zombie that touches it for a short time"
desc = """Freezes the first zombie that touches it for a short time
Damage: Nothing at all"""
[desc.puff_shroom]
name = "Calvatia cyathiformis"
short = "Costless short-ranged shooter"
desc = """Shoots short-ranged spores at zombies
Damage: Regular"""
[desc.sun_shroom]
name = "Pholiota aurivella"
short = "Gives you less sun at first. After some time, grows and gives regular sun"
desc = """Gives you less sun at first. After some time, grows and gives regular sun
Damage: This won't work"""
[desc.grave_buster]
name = "Idontknow nonplantae var. sepultura"
short = "Removes a grave"
desc = """Removes a grave on the planted tile
Damage: This should not exist"""
[desc.fume_shroom]
name = "Cortinarius archeri"
short = "Shoots fumes that can damage many zombies at once"
desc = """Shoots fumes that can pass through zombies
Damage: Regular
Area effect"""
[desc.scaredy_shroom]
name = "Cortinarius violaceus"
short = "Shoots at zombies, hides when zombies are around"
desc = """A long-range shooter, hides when zombies are around
Damage: Regular"""
[desc.ice_shroom]
name = "Clitocybe odora"
short = "Freezes all zombies on the screen"
desc = """Freezes all zombies on the screen
Damage: Just once, so what do you expect
One-use"""
[desc.doom_shroom]
name = "Tylopilus alboater"
short = "Blows up a large area of zombies"
desc = """Blows up a large area of zombies(actually full-screen as implemented)
Damage: SUPER
One-use"""
[desc.sun_bean]
name = "Phaseolus vulgaris"
short = "Gives you sun when a zombie touches it, gains more value over time"
desc = """Gives you sun when a zombie touches it, gains more value over time, so it is wise to plant early
Damage: (unsigned) NULL
One-use, work on touch"""
[desc.lily_pad]
name = "Nymphaeaceae ???"
short = "Lets you plant on water"
desc = """Lets you plant on water
Damage: Insane, or just nothing, what's the difference?
Aquatic plant"""
[desc.squash]
name = "Sechium edule"
short = "Squashes the first zombie in its range"
desc = """Squashes the first zombie in its range
Damage: SUPER"""
[desc.threepeater]
name = "Pisum sativum var. trijaculum"
short = "Shoots peas at three lanes"
desc = """Shoots peas at three lanes
Damage: Regular"""
