[desc.peashooter]
name = "Pisum sativum var. chlorojaculum"
short = "You would not see this anyway"
desc = """Shoots peas at zombies
Damage: Regular"""
[desc.sunflower]
name = "Helianthus annuus"
short = "Gives you more sun"
desc = """Throws sun that you can pick up, or not, I don't care anyway
Damage: Why Ask"""
[desc.cherry_bomb]
name = "Prunus avium"
short = "Blows up zombies in an area"
desc = """Deals great damage to zombies in an area(smaller than 3x3)]
Damage: SUPER
Works when planted"""
[desc.wall_nut]
name = "Juglans regia"
short = "Blocks zombies with its high health"
desc = """Blocks zombies
Damage: Not Again
Health: High"""
[desc.potato_mine]
name = "Solanum tuberosum"
short = "Blows up a small area of zombies on touch, takes time to arm himself"
desc = """Blows up a small area of zombies on touch, takes time to arm himself
Damage: SUPER
Takes time to be usable"""
[desc.snow_pea]
name = "Pisum sativum var. macrocarpum"
short = "Shoots peas that slow down zombies"
desc = """Shoots snow peas that can slow down zombies while dealing damage
Damage: Regular
Slows down zombies"""
[desc.repeater]
name = "Pisum sativum var. dijaculum"
short = "Shoots two peas at a time"
desc = """Shoots two peas at a time, saving you some space
Damage: Double"""
[desc.iceberg_lettuce]
name = "Lactuca sativa var. capitata"
short = "Freezes the first zombie that touches it for a short time"
desc = """Freezes the first zombie that touches it for a short time
Damage: Nothing at all"""
[desc.puff_shroom]
name = "Calvatia cyathiformis"
short = "Costless short-ranged shooter"
desc = """Shoots short-ranged spores at zombies
Damage: Regular"""
[desc.sun_shroom]
name = "Pholiota aurivella"
short = "Gives you less sun at first. After some time, grows and gives regular sun"
desc = """Gives you less sun at first. After some time, grows and gives regular sun
Damage: This won't work"""
[desc.grave_buster]
name = "Idontknow nonplantae var. sepultura"
short = "Removes a grave"
desc = """Removes a grave on the planted tile
Damage: This should not exist"""
[desc.fume_shroom]
name = "Cortinarius archeri"
short = "Shoots fumes that can damage many zombies at once"
desc = """Shoots fumes that can pass through zombies
Damage: Regular
Area effect"""
[desc.scaredy_shroom]
name = "Cortinarius violaceus"
short = "Shoots at zombies, hides when zombies are around"
desc = """A long-range shooter, hides when zombies are around
Damage: Regular"""
[desc.ice_shroom]
name = "Clitocybe odora"
short = "Freezes all zombies on the screen"
desc = """Freezes all zombies on the screen
Damage: Just once, so what do you expect
One-use"""
[desc.doom_shroom]
name = "Tylopilus alboater"
short = "Blows up a large area of zombies"
desc = """Blows up a large area of zombies(actually full-screen as implemented)
Damage: SUPER
One-use"""
[desc.sun_bean]
name = "Phaseolus vulgaris"
short = "Gives you sun when a zombie touches it, gains more value over time"
desc = """Gives you sun when a zombie touches it, gains more value over time, so it is wise to plant early
Damage: (unsigned) NULL
One-use, work on touch"""
[desc.lily_pad]
name = "Nymphaeaceae ???"
short = "Lets you plant on water"
desc = """Lets you plant on water
Damage: Insane, or just nothing, what's the difference?
Aquatic plant"""
[desc.squash]
name = "Sechium edule"
short = "Squashes the first zombie in its range"
desc = """Squashes the first zombie in its range
Damage: SUPER"""
[desc.threepeater]
name = "Pisum sativum var. trijaculum"
short = "Shoots peas at three lanes"
desc = """Shoots peas at three lanes
Damage: Regular"""
[desc.tall_nut]
name = "Juglans regia var. longium"
short = "Blocks zombies with its higggghhhh health"
desc = """Blocks zombies
Damage: Again?
Health: Very High"""
[desc.spikeweed]
name = "Centromadia pungens"
short = "Damages zombies that walk over it, able to destroy zombonis"
desc = """Damages zombies that walk over it, pokes a hole in zombonis' tires
Damage: Regular"""
[desc.torchwood]
name = "Burseraceae ??? "
short = "Lits anything that passes through"
desc = """Lits anything that passes through, doubling the damage, and deals splash damage
Damage: Supplementary"""
[desc.bonk_choy]
name = "Brassica rapa subsp. chinensis"
short = "Punches zombies in front of or behind it"
desc = """Punches zombies in front of or behind it, dealing high damage
Damage: High"""
[desc.jalapeno]
name = "Capsicum annuum"
short = "One-use, burns all zombies in one lane"
desc = """One-use, burns all zombies in one lane
Damage: SUPER"""
[desc.plantern]
name = "Idontknow nonplantae var. lucium"
short = "Removes the fog in an area"
desc = """Removes the fog in an area
Damage: (U)nreasonable"""
[desc.hurrikale]
name = "Brassica oleracea var. acephala"
short = "Blows zombies in its lane back"
desc = """Blows zombies in its lane back by 5 tiles
Damage: None"""
[desc.flower_pot]
name = "Idontknow nonplantae var. vasum"
short = "Lets you plant on higher places"
desc = """Lets you plant on higher places, or plant on the roof
Damage: u32::Default()"""
[desc.pumpkin]
name = "Cucurbita pepo"
short = "Protects plants/fungi inside it"
desc = """Protects plants/fungi inside it
Damage: Can you stop please?"""
[desc.starfruit]
name = "Averrhoa carambola"
short = "Shoots stars at five directions"
desc = """Shoots stars at arctan(1/2), arctan(-1/2), pi/2, -pi/2, and pi
Damage: 1.5x"""
[desc.magnet_shroom]
name = "Cortinarius iodes"
short = "Removes nearby magnetic items or pull up digger zombies"
desc = """Removes nearby magnetic items or pull up digger zombies for limited times
Damage: You can see the act of removing magnetic items as the "damage", but this does not work"""
[desc.blover]
name = "Trifolieae trifolium"
short = "Blows away fog, and kills balloon zombies"
desc = """Blows away fog and blows back zombies, works better for zombies in the air.
Unlike Brassica oleracea var. acephala, this can kill higher zombies
Damage: Maybe"""
[desc.cactus]
name = "Carnegiea gigantea"
short = "Shoots spikes that can go through zombies"
desc = """Shoots spike that can go through zombies
Damage: A little lower, but tripled"""
[desc.cabbage_pult]
name = "Brassica oleracea var. capitata"
short = "Lobs cabbages at zombies"
desc = """Lobs cabbages at zombies, unlike shooters, cabbages won't be blocked by terrain
Damage: Regular"""
[desc.coffee_bean]
name = "Coffea arabica"
short = "Wakes up fungi that sleep during the day"
desc = """Wakes up fungi that sleep during the day
Damage: In other words, the fungi it wakes may cause damage"""
[desc.kernel_pult]
name = "Zea mays"
short = "Lobs kernels, 1 butter, and repeat"
desc = """Lobs kernels at zombies, 1 butter, and repeat
Damage: Low(kernel) Regular(butter)"""
[desc.garlic]
name = "Allium sativum"
short = "Makes zombies go to other lanes when bitten"
desc = """Makes zombies go to other lanes when bitten
Damage: 0.0x(garlic)"""
[desc.melon_pult]
name = "Citrullus lanatus"
short = "Deals heavy damage to groups of zombies"
desc = """Deals heavy damage, and has good splash damage
Damage: High, but splash is medium"""
[desc.ethylene]
name = "Compressed Ethylene"
short = "Speeds up cooldown of plants"
desc = """Speeds cooldown of plants, and plants only
Damage: Basically nothing"""
[desc.sap_fling]
name = "Pinophyta ???"
short = "Slows groups of zombies"
desc = """Slows zombies in a 1x1 area
Damage: Surprisingly none"""
[desc.gold_bloom]
name = "Chrysogonum virginianum"
short = "Gives a burst of sun"
desc = """Gives you a burst of sun when planted
Damage: This is non-attacking"""
[desc.twin_sunflower]
name = "Helianthus annuus var. dihelio"
short = "Gives you more sun, more than just one"
desc = """Throws sun that you can pick up, or not, I do not care, seriously
Damage: It's getting more ridiculus"""
[desc.basic]
name = "Basic Zombie"
short = "A regular garden zombie"
desc = """The first zombie that ever invades your house
Health: Basic"""
[desc.roadcone]
name = "Conehead Zombie"
short = "A zombie with a road cone"
desc = """A little stronger zombie with a road cone
Health: Lv. 1"""
[desc.bucket]
name = "Buckethead Zombie"
short = "A zombie with a metal bucket"
desc = """A much stronger zombie with a metal bucket
Health: Lv. 3"""
[desc.flag]
name = "Flag Zombie"
short = "A fast, weak zombie with a flag"
desc = """A fast, weak zombie with a flag as a sign of incoming zombies
Health: Lv. 1-"""
[desc.all_star]
name = "All-Star Zombie"
short = "A powerful and strong zombie"
desc = """A strong zombie that delivers a powerful punch to your plants
Health: Lv. 2"""
[desc.newspaper]
name = "Newspaper Zombie"
short = "A zombie that gets really angry after the newspaper breaks"
desc = """A zombie that gets angry after the newspaper breaks, deals massive damage
Health: Lv. 2-"""
[desc.screen_door]
name = "Screen-Door Zombie"
short = "A zombie with screen-door, protecting it from being slowed down"
desc = """A strong zombie with a screen-door, protecting it from begin slowed down
Health: Lv. 3"""
[desc.trashcan]
name = "Trashcan Zombie"
short = "A zombie that pushes a trashcan onto your lawn"
desc = """A zombie that pushes a trashcan onto your lawn
Health: Lv. 2-"""
[desc.snorkel]
name = "Snorkel Zombie"
short = "A zombie that hides into the pool, avoiding attacks"
desc = """A zombie that hides into the pool, avoiding attacks
Health: Lv. 2"""
[desc.zomboni]
name = "Zomboni"
short = "A fast, strong zombie. Leaves trails."
desc = """A fast, strong zombie that leaves trails and challenges your defense line
Health: Lv. 3"""
[desc.dancing]
name = "Dancing Zombie"
short = "A zombie that summons other zombies to support its attack"
desc = """A zombie that summons other zombies to support its attack
Health: Lv. 2"""
[desc.jitb]
name = "Jack-in-the-box Zombie"
short = "A zombie that explodes on contact"
desc = """A very dangerous zombie that explodes on contact, dealing massive damage
Health: Lv. 1"""
[desc.balloon]
name = "Balloon Zombie"
short = "A zombie that flies over most of your defense, however, can be hit with taller plants"
desc = """A zombie that can fly over most of your defense, however, can be defended using flower pots can lobbing plants
Health: Basic"""
[desc.digger]
name = "Digger Zombie"
short = "A zombie that digs through the lawn"
desc = """A zombie that digs through the lawn, and attacks from the back
Health: Lv. 1-"""
[desc.pogo]
name = "Pogo Zombie"
short = "A jumping zombie that goes over your plants"
desc = """A jumping zombie over your plants, but can be blocked using tall plants
Health: Lv. 1"""
[desc.gargantuar]
name = "Gargantuar"
short = "A huge and strong zombie that can smash your plants"
desc = """A huge and strong zombie that smashes your plants
Health: Lv. 6"""
[desc.baseball]
name = "Baseball Zombie"
short = "A zombie that throws baseballs at your most costly plant"
desc = """A zombie that targets your most costly plant, hitting it with baseballs
Health: Lv. 1"""
[desc.rally]
name = "Rally Zombie"
short = "A zombie that leads to extreme attacks!"
desc = """A zombie that speeds up nearing zombies, often leading to an extreme attack
Health: Lv. 1"""
[desc.brick]
name = "Brickhead Zombie"
short = "A very strong zombie"
desc = """A very strong zombie with bricks on its head
Health: Lv. 5"""
[desc.giga]
name = "Giga-All-Star Zombie"
short = "A zombie that delivers unstoppable attacks"
desc = """A powerful zombie that corrodes into your defense line
Health: Lv. 4"""
[desc.sunedit]
name = "Sunday Edition Zombie"
short = "A strong zombie that gets really angry after the magazine breaks"
desc = """A strong zombie that gets angry after the magazine breaks
Health: Lv. 5"""
[desc.mirror]
name = "Mirror Zombie"
short = "I know this is from Hoot"
desc = """A zombie that repels projectiles with it mirror
Health: Lv. 3-"""
[desc.foodcan]
name = "Foodcan Zombie"
short = "A zombie that pushes a foodcan"
desc = """A zombies that pushes a foodcan, which can absorb projectiles that are not strong enough
Health: Lv. 1"""
[desc.hidden]
name = "Hidden Zombie"
short = "This is"
desc = "You win."
