map = [
    [
        { stage = 2, level = 1 },
        [
            "Greetings, you.",
            "I'm sorry that I'm NOT sorry for showing up late.",
            "You should've listened to me.",
            "Check this game out at impodog's github account.",
            "DO IT OR I'LL SPAWN MORE ZOMBIES",
        ],
    ],
    [
        { stage = 2, level = 5 },
        [
            "Tell you what.",
            "This is a fun level to play!",
            "Use your hammer to smash those zombies!",
        ],
    ],
    [
        { stage = 2, level = 10 },
        [
            "I've heard about Max.",
        ],
    ],
    [
        { stage = 3, level = 1 },
        [
            "Fungi are no good stuff.",
            "It appears that they've planned to spend the day sleeping!",
            "Pro tip: use Nymphaeaceae to plant terrestrial stuff on water.",
        ],
    ],
    [
        { stage = 3, level = 5 },
        [
            "In this level, your shooters will shoot quicker over time!",
            "Plant peashooters to release a powerful burst!",
        ],
    ],
    [
        { stage = 4, level = 1 },
        [
            "That's all this version has got, thanks for playing!",
        ],
    ],
]
