map = [
    [
        [2, 1],
        [
            "Greetings, you.",
            "I'm sorry that I'm NOT sorry for showing up late.",
            "You should've listened to me.",
            "Check this game out at impodog's github account.",
            "DO IT OR I'LL SPAWN MORE ZOMBIES",
        ],
    ],
    [
        [2, 5],
        [
            "Tell you what.",
            "This is a fun level to play!",
            "Use your hammer to smash those zombies!",
        ],
    ],
    [
        [2, 10],
        [
            "I've heard about Max.",
        ],
    ],
    [
        [3, 1],
        [
            "Fungi are no good stuff.",
            "It appears that they've planned to spend the day sleeping!",
            "Pro tip: use Nymphaeaceae to plant terrestrial stuff on water.",
        ],
    ],
    [
        [3, 5],
        [
            "In this level, your shooters will shoot quicker over time!",
            "Plant peashooters to release a powerful burst!",
        ],
    ],
    [
        [4, 1],
        [
            "Here we are into the night fall.",
        ],
    ],
    [
        [4, 3],
        [
            "Pro tip #2: DO use flower pots to hit higher targets, and tall-nuts to defend against them.",
        ],
    ],
    [
        [4, 10],
        [
            "Why'd it get so dark all of a sudden?",
            "This can't be good.",
        ],
    ],
    [
        [5, 1],
        [
            "Pro tip #3: Shooters will hit the roof. Use lobbers instead.",
        ],
    ],
    [
        [5, 5],
        [
            "This level lets you plant 5 creatures in a row!",
        ],
    ],
    [
        [1, 11],
        [
            "Welcome to expansion levels.",
            "This pack of levels is intended for hardcore players, thus casual players may find their gaming experience unpleasant. Be warned.",
        ],
    ],
    [
        [2, 11],
        [
            "So we've got a survivor.",
        ],
    ],
]
