map = [
    [
        { stage = 2, level = 1 },
        [
            "Greetings, you.",
            "I'm sorry that I'm NOT sorry for showing up late.",
            "You should've listened to me.",
            "Check this game out at impodog's github account.",
            "DO IT OR I'LL SPAWN MORE ZOMBIES",
        ],
    ],
    [
        { stage = 2, level = 5 },
        [
            "Tell you what.",
            "This is a fun level to play!",
            "Use your hammer to smash those zombies!",
        ],
    ],
    [
        { stage = 2, level = 10 },
        [
            "I've heard about Max.",
        ],
    ],
    [
        { stage = 3, level = 1 },
        [
            "Fungi are no good stuff.",
            "It appears that they've planned to spend the day sleeping!",
            "Pro tip: use Nymphaeaceae to plant terrestrial stuff on water.",
        ],
    ],
    [
        { stage = 3, level = 5 },
        [
            "In this level, your shooters will shoot quicker over time!",
            "Plant peashooters to release a powerful burst!",
        ],
    ],
    [
        { stage = 4, level = 1 },
        [
            "When the night falls...",
        ],
    ],
    [
        { stage = 4, level = 3 },
        [
            "Pro tip #2: DO use flower pots to hit higher targets, and tall-nuts to defend against them.",
        ],
    ],
    [
        { stage = 4, level = 10 },
        [
            "Why'd it get so dark all of a sudden?",
            "This can't be good.",
        ],
    ],
    [
        { stage = 5, level = 1 },
        [
            "Pro tip #3: Shooters will hit the roof. Use lobbers instead.",
        ],
    ],
    [
        { stage = 5, level = 5 },
        [
            "This level lets you plant 5 creatures in a row!",
        ],
    ],
]
