[config]
layout = "Day"
game = "Adventure"
selection = { "All" = [-1] }
sun = 150
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1]]
avail = [1]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2]]
avail = [1]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2]]
avail = [1]
[[waves]]
points = 0
wait = 60.0
big = false
fixed = [[1, 4]]
avail = [1]
[[waves]]
points = 0
wait = 60.0
big = false
fixed = [[1, 5]]
avail = [1]
