[config]
selection = { "All" = [-1, -2, -3, -4, -5, -6, -7, -8] }
layout = "Day"

modify = { give = -9, next = { stage = 2, level = 1 }, slots = 7 }
sun = 1000
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[1, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = true
fixed = [[4, 1], [1, 1], [2, 1], [3, 1], [5, 1]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = true
fixed = [[4, 2], [1, 3], [2, 3], [3, 2], [5, 1]]
avail = []
[[waves]]
points = 400
wait = 60.0
big = true
fixed = [[4, 3], [1, 5], [3, 3], [5, 2]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 80.0
big = true
fixed = [[4, 4], [1, 5], [2, 5], [5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 600
wait = 80.0
big = true
fixed = [[4, 5], [1, 10], [5, 2]]
avail = [2, 3, 5]
[[waves]]
points = 700
wait = 60.0
big = true
fixed = [[4, 6], [5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 800
wait = 70.0
big = true
fixed = [[4, 7], [1, 8], [5, 3]]
avail = [2, 3]
[[waves]]
points = 900
wait = 60.0
big = true
fixed = [[4, 8], [2, 5], [3, 5], [5, 1]]
avail = [1, 5]
[[waves]]
points = 1000
wait = 80.0
big = true
fixed = [[4, 9], [1, 6], [5, 8]]
avail = [1, 2, 3]
