[config]
layout = "Day"
selection = "Any"
modify = { give = 0, next = [1, 14] }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 2]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 2], [7, 1]]
avail = []
[[waves]]
points = 175
wait = 40.0
big = false
fixed = [[302, 1]]
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[1, 5]]
avail = [2, 3, 7]
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[301, 1], [302, 1], [2, 3], [3, 1]]
avail = [1, 2, 3]
[[waves]]
points = 350
wait = 40.0
big = false
fixed = [[302, 1], [3, 1]]
avail = [1, 2]
[[waves]]
points = 450
wait = 40.0
big = false
fixed = [[1, 2], [2, 2]]
avail = [1, 3, 7]
[[waves]]
points = 550
wait = 30.0
big = false
fixed = [[1, 4], [3, 1]]
avail = [2, 3, 302]
[[waves]]
points = 700
wait = 40.0
big = false
fixed = [[1, 3], [2, 3]]
avail = [2, 3]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[301, 2], [302, 3], [3, 3], [7, 1]]
avail = [1, 2, 7]
