[config]
layout = "Day"
selection = "Any"
modify = { give = 0, next = { stage = 1, level = 15 } }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [6, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[302, 1], [1, 3]]
avail = []
[[waves]]
points = 250
wait = 30.0
big = false
fixed = [[3, 1], [6, 2]]
avail = [1, 2]
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 1], [2, 1], [302, 1]]
avail = [2, 3]
[[waves]]
points = 400
wait = 50.0
big = true
fixed = [[301, 1], [302, 1], [6, 2]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[1, 2]]
avail = [1, 2, 3, 302]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[3, 3], [6, 1]]
avail = [1, 2]
[[waves]]
points = 600
wait = 30.0
big = false
fixed = [[1, 2], [3, 1], [6, 1]]
avail = [2, 3, 6]
[[waves]]
points = 650
wait = 40.0
big = false
fixed = [[1, 3], [2, 1], [302, 2]]
avail = [1, 2, 3, 6]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[301, 2], [1, 2], [3, 1], [6, 3], [302, 3]]
avail = [1, 2, 6, 302]
