[config]
layout = "Day"
selection = { "All" = [-2, -3, -18, -101] }
modify = { give = 0, next = [1, 16] }
sun = 200
bgm = "Lb"
publish = { name = "Bowling (Ex)" }
[[waves]]
points = 0
wait = 20.0
big = false
fixed = [[1, 5], [302, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 3], [3, 2]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[10, 1], [1, 3]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 4], [2, 2], [11, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 3], [2, 3], [10, 1], [302, 2]]
avail = []
[[waves]]
points = 450
wait = 50.0
big = true
fixed = [[301, 1], [5, 1], [11, 2]]
avail = [1, 2, 3, 302]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[1, 5], [2, 1]]
avail = [2, 3]
[[waves]]
points = 400
wait = 30.0
big = false
fixed = [[1, 3], [302, 2]]
avail = [1, 2, 3, 10]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 5], [2, 3], [10, 3]]
avail = []
[[waves]]
points = 600
wait = 30.0
big = false
fixed = [[1, 3]]
avail = [2, 3, 302]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[5, 1], [10, 1], [11, 3]]
avail = [1, 2]
[[waves]]
points = 800
wait = 50.0
big = false
fixed = [[301, 2], [5, 2]]
avail = [2, 3, 10, 11, 302]
