[config]
layout = "Day"
selection = "Any"
modify = { give = 0, next = { stage = 1, level = 17 } }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 4]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [2, 1], [3, 2]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3], [5, 1], [302, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 3], [2, 2], [3, 2], [6, 1]]
avail = []
[[waves]]
points = 300
wait = 50.0
big = true
fixed = [[301, 1], [1, 3], [302, 1]]
avail = [2, 3, 6]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[5, 1], [6, 1]]
avail = [1, 3, 6, 302]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 3], [2, 3], [3, 3], [6, 3], [302, 1]]
avail = []
[[waves]]
points = 300
wait = 30.0
big = false
fixed = [[1, 2], [5, 2], [302, 1]]
avail = [2, 3]
[[waves]]
points = 500
wait = 40.0
big = false
fixed = [[3, 1], [5, 1]]
avail = [2, 6, 302]
[[waves]]
points = 600
wait = 50.0
big = true
fixed = [[301, 2], [1, 4], [5, 3], [302, 3]]
avail = [1, 2, 3, 6]
