[config]
layout = "Day"
selection = "Any"
modify = { give = 0, next = { stage = 1, level = 17 } }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 2]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [3, 1], [7, 1]]
avail = []
[[waves]]
points = 300
wait = 40.0
big = false
fixed = [[1, 2], [302, 1]]
avail = [3, 7]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [2, 2], [7, 1], [303, 1]]
avail = []
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[3, 1], [302, 1]]
avail = [1, 2, 302]
[[waves]]
points = 500
wait = 30.0
big = false
fixed = [[3, 2], [303, 1]]
avail = [1, 2, 7]
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 5], [302, 2]]
avail = [2, 3]
[[waves]]
points = 800
wait = 50.0
big = true
fixed = [[301, 1], [303, 2]]
avail = [1, 2, 3, 7, 303]
