[config]
layout = "Day"
selection = "Any"
modify = { give = 0, next = { stage = 1, level = 18 } }
sun = 75
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 4]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2], [2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 1], [3, 1], [303, 1]]
avail = []
[[waves]]
points = 200
wait = 30.0
big = false
fixed = [[302, 1], [6, 1]]
avail = [1, 2]
[[waves]]
points = 300
wait = 50.0
big = true
fixed = [[301, 1], [302, 2], [303, 1], [5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 350
wait = 30.0
big = false
fixed = [[1, 3], [2, 3], [302, 2]]
avail = [3, 6]
[[waves]]
points = 400
wait = 40.0
big = false
fixed = [[1, 2], [303, 1]]
avail = [2, 3]
[[waves]]
points = 450
wait = 30.0
big = false
fixed = [[302, 3]]
avail = [1, 2, 3, 6]
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 5], [2, 4], [3, 3], [6, 3], [303, 1]]
avail = []
[[waves]]
points = 500
wait = 50.0
big = true
fixed = [[301, 2], [1, 7], [302, 3], [303, 3]]
avail = [2, 3, 6]
