[config]
layout = "Day"
selection = "Any"
game = ["InfiSun"]
modify = { give = -301, next = { stage = 2, level = 11 } }
sun = 0xbadeffec
bgm = "Ub"
publish = { name = "War of the Day" }
[[waves]]
points = 0
wait = 0.0
big = false
fixed = [[1, 1]]
avail = []
[[waves]]
points = 0
wait = 10.0
big = true
fixed = [[1, 1], [2, 1], [3, 1], [5, 1], [11, 1], [301, 1], [302, 1], [303, 1]]
avail = []
[[waves]]
points = 500
wait = 20.0
big = true
fixed = [[301, 2], [303, 3], [10, 3]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 500
wait = 20.0
big = true
fixed = [[301, 3], [1, 10], [5, 2], [303, 3], [6, 5]]
avail = [2, 3, 5, 7, 10]
[[waves]]
points = 700
wait = 30.0
big = true
fixed = [[301, 4], [302, 5], [10, 1], [11, 1]]
avail = [1, 2, 3, 5, 6, 7, 8]
[[waves]]
points = 800
wait = 30.0
big = true
fixed = [[301, 5], [302, 3], [303, 3], [7, 10]]
avail = [1, 2, 3, 5, 6]
[[waves]]
points = 900
wait = 30.0
big = true
fixed = [[301, 6], [303, 5]]
avail = [1, 2, 3, 5, 6, 7]
[[waves]]
points = 900
wait = 20.0
big = true
fixed = [[1, 10], [301, 7], [10, 5], [11, 3]]
avail = [2, 3, 5, 6, 7, 302]
[[waves]]
points = 900
wait = 20.0
big = true
fixed = [[1, 20], [301, 8], [5, 3], [303, 3], [10, 2], [11, 5]]
avail = [2, 3, 6, 7, 302]
[[waves]]
points = 1000
wait = 30.0
big = true
fixed = [[301, 9], [303, 3], [303, 3], [5, 3], [10, 5], [11, 10]]
avail = [1, 2, 3, 6, 7, 302]
[[waves]]
points = 1500
wait = 50.0
big = true
fixed = [[301, 10], [303, 10], [5, 5], [10, 5], [11, 10]]
avail = [1, 2, 3, 6, 7, 302]
