[config]
layout = "Day"
selection = { "All" = [-2, -3, -101] }
modify = { give = -5, next = { stage = 1, level = 6 } }
sun = 125
bgm = "Lb"
publish = { name = "Bowling" }
[[waves]]
points = 0
wait = 20.0
big = false
fixed = [[1, 5], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 5], [2, 3]]
avail = []
[[waves]]
points = 200
wait = 40.0
big = false
fixed = [[2, 2], [3, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 50.0
big = false
fixed = [[3, 2]]
avail = [1, 2, 3]
[[waves]]
points = 1000
wait = 70.0
big = true
fixed = []
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 50.0
big = false
fixed = []
avail = [1, 2, 3]
[[waves]]
points = 200
wait = 60.0
big = false
fixed = [[3, 3]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 50.0
big = false
fixed = [[2, 3]]
avail = [2, 3]
[[waves]]
points = 1500
wait = 60.0
big = true
fixed = [[3, 2]]
avail = [1, 2, 3]
