[config]
layout = "Day"
selection = { "All" = [-1, -2, -3, -4, -5] }
modify = { give = -6, next = { stage = 1, level = 7 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 2]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[2, 1], [3, 1]]
avail = []
[[waves]]
points = 200
wait = 60.0
big = false
fixed = [[1, 2], [2, 1]]
avail = [2, 3]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[2, 2], [3, 1]]
avail = [1, 2, 3]
[[waves]]
points = 300
wait = 60.0
big = false
fixed = [[1, 5]]
avail = [2, 3]
[[waves]]
points = 900
wait = 70.0
big = true
fixed = []
avail = [1, 2, 3]
