[config]
layout = "Day"
game = "Adventure"
selection = { "All" = [-1, -2, -3, -4, -5] }
modify = { give = -6, next = { stage = 1, level = 7 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 1], [3, 1]]
avail = []
[[waves]]
points = 0
wait = 40.0
big = false
fixed = [[1, 2], [2, 1]]
avail = []
[[waves]]
points = 200
wait = 60.0
big = false
fixed = [[3, 1]]
avail = [1, 2, 3]
[[waves]]
points = 500
wait = 80.0
big = true
fixed = [[4, 1], [2, 3], [5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 40.0
big = false
fixed = [[1, 3]]
avail = [2, 3]
[[waves]]
points = 200
wait = 60.0
big = false
fixed = [[5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 150
wait = 70.0
big = false
fixed = [[3, 2]]
avail = [1, 2]
[[waves]]
points = 800
wait = 80.0
big = true
fixed = [[4, 2], [2, 2]]
avail = [1, 2, 3, 5]
