[config]
layout = "Day"
game = "Adventure"
selection = "Any"
modify = { give = -8, next = { stage = 1, level = 9 } }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[1, 1], [2, 2]]
avail = []
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 1], [2, 1], [3, 1], [5, 1]]
avail = []
[[waves]]
points = 300
wait = 60.0
big = false
fixed = [[1, 2]]
avail = [1, 2, 3]
[[waves]]
points = 700
wait = 80.0
big = true
fixed = [[4, 1], [5, 2]]
avail = [1, 2, 3]
[[waves]]
points = 0
wait = 50.0
big = false
fixed = [[1, 5], [2, 2], [3, 2]]
avail = []
[[waves]]
points = 250
wait = 60.0
big = false
fixed = [[1, 4], [5, 1]]
avail = [2, 3]
[[waves]]
points = 250
wait = 50.0
big = false
fixed = [[1, 3], [3, 3]]
avail = [1, 2, 3]
[[waves]]
points = 1000
wait = 70.0
big = true
fixed = [[4, 2], [1, 4], [2, 3], [5, 3]]
avail = [1, 2, 3]
