[config]
layout = "Day"
selection = "Any"
modify = { give = -8, next = [1, 9] }
sun = 50
[[waves]]
points = 0
wait = 30.0
big = false
fixed = [[2, 1], [3, 1]]
avail = []
[[waves]]
points = 150
wait = 40.0
big = false
fixed = [[5, 1]]
avail = [1, 2]
[[waves]]
points = 200
wait = 50.0
big = false
fixed = [[2, 1]]
avail = [1, 2, 3]
[[waves]]
points = 250
wait = 60.0
big = false
fixed = [[1, 2], [5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 600
wait = 80.0
big = true
fixed = [[4, 1], [5, 1]]
avail = [1, 2, 3]
[[waves]]
points = 0
wait = 60.0
big = false
fixed = [[1, 5], [2, 2], [3, 2]]
avail = []
[[waves]]
points = 150
wait = 50.0
big = false
fixed = [[5, 2]]
avail = [1, 2, 3]
[[waves]]
points = 400
wait = 50.0
big = false
fixed = []
avail = [1, 2, 3]
[[waves]]
points = 1200
wait = 70.0
big = true
fixed = [[4, 2], [5, 2]]
avail = [1, 2, 3]
