[rally]
velocity = [-0.27, -0.265]
rally_flag_box = { width = 0.7, height = 1.0 }
range = { x = [-1.5, 1.5], y = [-1.5, 1.5], z = [-0.5, 0.5] }
boost = 1.5
rally_flag_health = 400
damage = 60
interval = 0.4
cooldown = 5.0
cost = 125
[brick]
brick_box = { width = 0.5, height = 0.5 }
brick_health = 2200
cooldown = 5.0
cost = 175
[giga]
velocity_running = [-1.7, -1.695]
velocity = [-0.095, -0.09]
self_box = { width = 0.7, height = 1.2 }
helmet_box = { width = 0.4, height = 0.4 }
slide_distance = 2.8
self_health = [250, 50]
helmet_health = 1500
damage = 60
interval = 0.8
tackle_damage = 2000
cooldown = 7.5
cost = 250
