[rally]
velocity = [-0.27, -0.265]
rally_flag_box = { width = 0.7, height = 1.0 }
range = { x = [-1.5, 1.5], y = [-1.5, 1.5], z = [-0.5, 0.5] }
boost = 1.5
rally_flag_health = 400
damage = 60
interval = 0.4
cooldown = 5.0
cost = 125
[brick]
brick_box = { width = 0.5, height = 0.5 }
brick_health = 2200
cooldown = 5.0
cost = 175
[giga]
velocity_running = [-1.7, -1.695]
velocity = [-0.095, -0.09]
self_box = { width = 0.7, height = 1.2 }
helmet_box = { width = 0.4, height = 0.4 }
slide_distance = 2.8
self_health = [250, 50]
helmet_health = 1500
damage = 60
interval = 0.8
tackle_damage = 2000
cooldown = 7.5
cost = 250
[sunedit]
velocity = [-0.095, -0.09]
rage_velocity = [-0.365, -0.36]
self_box = { width = 0.6, height = 1.1 }
sunedit_box = { width = 0.7, height = 0.8 }
self_health = [420, 70]
sunedit_health = 1800
damage = 60
interval = 0.6
rage_interval = 0.15
cooldown = 7.5
cost = 250
[mirror]
mirror_box = { width = 0.5, height = 1.0 }
mirror_health = 550
cooldown = 5.0
cost = 200
[foodcan]
velocity = [-0.155, -0.15]
self_box = { width = 0.6, height = 1.1 }
foodcan_box = { width = 0.4, height = 0.4 }
self_health = [350, 70]
foodcan_health = [200, 0]
damage = 60
foodcan_damage = 150
interval = 0.6
cooldown = 4.0
cost = 175
