[peashooter]
velocity = 0.1
self_box = { width = 1.0, height = 1.0 }
pea_box = { width = 0.3, height = 0.3 }
times = 1
health = 300
damage = 20
interval = 1.5
cooldown = 7.5
cost = 100
[sunflower]
velocity = { x = [-0.05, 0.05], y = [-0.03, 0.03], z = 0.1, r = 0.1 }
self_box = { width = 1.0, height = 1.0 }
health = 300
interval = 24.0
cooldown = 7.5
cost = 50
multiplier = 1.0
[cherry_bomb]
self_box = { width = 1.0, height = 1.0 }
boom_box = { width = 2.5, height = 2.5 }
health = 4000
damage = 1800
cooldown = 50.0
countdown = 1.0
animation_time = 3.0
cost = 150
[wall_nut]
self_box = { width = 0.7, height = 0.9 }
health = 4000
cooldown = 30.0
cost = 50
[potato_mine]
self_box = { width = 1.0, height = 0.4 }
boom_box = { width = 1.0, height = 1.0 }
health = 400
damage = 1800
prepare = 25.0
cooldown = 30.0
animation_time = 3.0
cost = 25
[snow_pea]
velocity = 0.09
self_box = { width = 1.0, height = 1.0 }
pea_box = { width = 0.3, height = 0.3 }
snow = { duration = 10.0, factor = 0.5 }
times = 1
health = 200
damage = 20
interval = 1.5
cooldown = 7.5
cost = 175
[repeater]
velocity = 0.11
self_box = { width = 1.0, height = 1.0 }
times = 2
health = 300
damage = 20
interval = 1.5
cooldown = 7.5
cost = 225
[iceberg_lettuce]
self_box = { width = 0.8, height = 0.7 }
snow = { duration = 10.0, factor = 0.0 }
health = 200
cooldown = 7.5
cost = 25
[bowling_nut]
velocity = { x = 0.075, y = 0.05, z = 0.0, r = -0.15 }
self_box = { width = 0.7, height = 0.9 }
health = 4000
damage = 300
cooldown = 2.0
cost = 75
