[basic]
velocity = [-0.0035, -0.0025]
self_box = { width = 0.5, height = 1.2 }
arm_box = { width = 0.2, height = 0.6 }
self_health = [100, 70]
arm_health = 100
damage = 20
interval = 0.2
cooldown = 1.0
cost = 50
[roadcone]
roadcone_box = { width = 0.3, height = 0.6 }
roadcone_health = 370
cooldown = 1.5
cost = 75
[bucket]
bucket_box = { width = 0.5, height = 0.5 }
bucket_health = 1100
cooldown = 2.0
cost = 125
[flag]
velocity = [-0.006, -0.005]
flag_box = { width = 0.5, height = 0.8 }
flag_health = 100
cooldown = 1.5
cost = 75
[all_star]
velocity_running = [-0.06, -0.05]
velocity = [-0.0025, -0.002]
self_box = { width = 0.7, height = 1.2 }
helmet_box = { width = 0.4, height = 0.4 }
self_health = [250, 50]
helmet_health = 800
damage = 20
interval = 0.3
tackle_damage = 2000
cooldown = 5.0
cost = 175
[newspaper]
velocity = [-0.0035, -0.0025]
rage_velocity = [-0.014, -0.012]
self_box = { width = 0.6, height = 1.1 }
newspaper_box = { width = 0.5, height = 0.5 }
self_health = [300, 70]
newspaper_health = 250
damage = 20
interval = 0.2
rage_interval = 0.05
cooldown = 5.0
cost = 150
[screen_door]
screen_door_box = { width = 0.5, height = 1.0 }
screen_door_health = 1100
cooldown = 5.0
cost = 150
