[basic]
velocity = [-0.004, -0.003]
self_box = { width = 0.5, height = 1.2 }
arm_box = { width = 0.2, height = 0.6 }
self_health = [100, 70]
arm_health = 100
damage = 20
interval = 0.3
cooldown = 1.0
cost = 50
