[basic]
velocity = [-0.0035, -0.0025]
self_box = { width = 0.5, height = 1.2 }
arm_box = { width = 0.2, height = 0.6 }
self_health = [100, 70]
arm_health = 100
damage = 20
interval = 0.3
cooldown = 1.0
cost = 50
[roadcone]
roadcone_box = { width = 0.3, height = 0.6 }
roadcone_health = 370
cooldown = 1.5
cost = 75
[bucket]
bucket_box = { width = 0.5, height = 0.5 }
bucket_health = 1100
cooldown = 2.0
cost = 125
