[basic]
velocity = [-0.095, -0.09]
self_box = { width = 0.5, height = 1.2 }
arm_box = { width = 0.2, height = 0.6 }
self_health = [100, 70]
arm_health = 100
damage = 60
interval = 0.6
cooldown = 1.0
cost = 50
[roadcone]
roadcone_box = { width = 0.3, height = 0.6 }
roadcone_health = 370
cooldown = 1.5
cost = 75
[bucket]
bucket_box = { width = 0.5, height = 0.5 }
bucket_health = 1100
cooldown = 2.0
cost = 125
[flag]
velocity = [-0.185, -0.18]
flag_box = { width = 0.5, height = 0.8 }
flag_health = 100
cooldown = 1.5
cost = 75
[all_star]
velocity_running = [-1.5, -1.495]
velocity = [-0.095, -0.09]
self_box = { width = 0.7, height = 1.2 }
helmet_box = { width = 0.4, height = 0.4 }
self_health = [250, 50]
helmet_health = 800
damage = 60
interval = 0.8
tackle_damage = 2000
cooldown = 5.0
cost = 175
[newspaper]
velocity = [-0.095, -0.09]
rage_velocity = [-0.365, -0.36]
self_box = { width = 0.6, height = 1.1 }
newspaper_box = { width = 0.5, height = 0.5 }
self_health = [400, 70]
newspaper_health = 250
damage = 60
interval = 0.6
rage_interval = 0.15
cooldown = 5.0
cost = 150
[screen_door]
screen_door_box = { width = 0.5, height = 1.0 }
screen_door_health = 1100
cooldown = 5.0
cost = 150
[trashcan]
velocity = [-0.105, -0.1]
self_box = { width = 0.6, height = 1.1 }
trashcan_box = { width = 0.4, height = 0.5 }
self_health = [350, 70]
trashcan_health = [500, 0]
damage = 60
trashcan_damage = 150
interval = 0.6
cooldown = 4.0
cost = 125
[hidden]
velocity = [-0.105, -0.1]
self_box = { width = 1.0, height = 2.0 }
self_health = [3600, 0]
damage = 60
interval = 0.1
cooldown = 800.0
cost = 800
[tube]
self_box = { width = 0.6, height = 0.3 }
[snorkel]
velocity = [-0.105, -0.1]
self_box = { width = 0.5, height = 1.1 }
underwater_box = { width = 0.4, height = 0.3 }
self_health = [350, 70]
damage = 60
interval = 0.6
cooldown = 1.5
cost = 75
[zomboni]
velocity = [-0.19, -0.185]
self_box = { width = 2.0, height = 1.5 }
self_health = [1300, 200]
damage = 2000
interval = 0.6
cooldown = 5.0
cost = 200
[dancing]
velocity_back = [-0.55, -0.545]
velocity = [-0.085, -0.08]
self_box = { width = 0.6, height = 1.2 }
backup_box = { width = 0.5, height = 1.2 }
self_health = [570, 70]
backup_health = [200, 70]
damage = 60
interval = 0.6
back_time = 5.5
spawn_interval = 7.0
cooldown = 4.0
cost = 250
[jitb]
velocity = [-0.19, -0.185]
self_box = { width = 0.6, height = 1.1 }
range = { x = [-1.0, 1.0], y = [-1.0, 1.0], z = [-0.01, 0.01] }
self_health = [570, 70]
damage = 2000
animation_time = 3.0
cooldown = 7.5
cost = 200
